# -*- coding: utf-8 -*-
"""Extraccion_datos_tweepy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t9mjy5rCG9-q4BjrycjQA8Cg2eEHtkcd
"""

import tweepy
import csv

# API's keys and tokens
CONSUMER_KEY = "put here your consumer key"
CONSUMER_SECRET = "put here your consumer secret"
ACCESS_TOKEN = "put here your access token"
ACCESS_TOKEN_SECRET = "put here your access token secret"

#  Parameters
min_len = 10  # Min length of our tweets
n_tweets = 10  # Number of tweets to mine
date = "2017-04-03"  # Filter by date
query = "#Covid_19ec -filter:retweets"

# Start the session
auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)

api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)

# Create the file and the writer
csvFile = open('last_tweets_ecuador.csv', 'a', encoding='utf-8')  # ENCODING!!!
csvWriter = csv.writer(csvFile)
csvWriter.writerow(['date', 'tweet'])  # 'Create' the column names

counter = 0  # To count the total tweets mined

# Save the tweets with more than 'min_len' chars in our file. Ignore retweets
for tweet in (tweepy.Cursor(api.search,
                            q=query,  # Ignore retweets
                            lang="es",  # Only in spanish
                            since=date)  # Filter by date
        .items(n_tweets)):  # 'n_tweets' in total

 if len(tweet.text) >= min_len:
  csvWriter.writerow([tweet.created_at, tweet.text])  # TODO: encoding utf-8 del csv
  print(tweet.text)
  counter += 1

# Chek the size of our .csv file
print(counter, 'total tweets mined with a minimum length of', min_len, 'characters each.')

# Close the file to avoid problems
csvFile.close()


